### ISSUE TITLE
Issue: breaks all websites that it runs on

### ISSUE THREAD

**Issue by azuravian** [webtoplex/browser-extension#5]
**Describe the bug**
When sites are enabled, the text and images on the site are shifted around so as to make the site unusable.  Even the WebtoPlex menu at the bottom left has it's buttons overlapping when you hover over it.

**To Reproduce**
1. Turn on supported any website in the WebtoPlex options.
2. Go to that site.
3. Navigate to a page with a movie
4. Site will have text and images shifted to incorrect locations on screen.

**Expected behavior**
Site will behave as normal, but will have usable WebtoPlex menu at the bottom of the screen.

**Screenshots**
What it looks like with extension enabled and turned on for Letterboxd.
![Broken Site](https://user-images.githubusercontent.com/7379812/81466726-cb03af80-91a1-11ea-8fe6-c23efdf5a608.jpg)
WebtoPlex menu
![Broken menu](https://user-images.githubusercontent.com/7379812/81466729-cdfea000-91a1-11ea-8737-fb11934e5717.jpg)
Letterboxd with extension disabled.
![Normal Site](https://user-images.githubusercontent.com/7379812/81466730-d060fa00-91a1-11ea-8799-f764ab3fb6ef.jpg)

**Extension Information**
 - Version: `4.1.2.4`
 - Source: `Edge Store` linked to from `GitHub`
 - Browser: `edge`

**Additional comments**
This also effects local sites, such as Sonarr and Radarr.  I also tested this using Chrome, with the same results.

**Comment by Ephellon** [comment]
Already on original thread. See [SpaceK33z:webtoplex#165](https://github.com/SpaceK33z/web-to-plex/issues/165)

Please change the button type to box, enable `Developer mode`, and reload.
