### ISSUE TITLE
Issue: [Something Broke]

### ISSUE THREAD

**Issue by pabohoney1** [webtoplex/browser-extension#6]
**Describe the bug**
This is breaking formatting on a lot of sites, namely Github, Radarr, YouTube and IMDB as these are the only ones I noticed before I had to shut the extension off.

**To Reproduce**
1. Enable the plugin
2. Browse to one of the sites

**Expected behavior**
Site formatting should not be affected by this plugin

**Screenshots**
![imdb](https://user-images.githubusercontent.com/11789756/85142428-3a3add80-b1fd-11ea-88f7-93a6c54f2d66.jpg)
![radarr](https://user-images.githubusercontent.com/11789756/85142430-3ad37400-b1fd-11ea-9a82-cc23b27e52b0.jpg)
![youtube](https://user-images.githubusercontent.com/11789756/85142432-3ad37400-b1fd-11ea-829b-a5ac7955f46d.jpg)
![github](https://user-images.githubusercontent.com/11789756/85142433-3b6c0a80-b1fd-11ea-8c34-ebd2b523f432.jpg)

**Extension Information**
 - Version: `4.1.2.4`
 - Source: `store`
 - Browser: `chrome`

**Comment by pabohoney1** [comment]
Nevermind, looks like this is not the correct github location and the issue is reported in the correct one (https://github.com/SpaceK33z/web-to-plex/)

**Comment by Ephellon** [comment]
Hi. Yes, the link provided is the parent version.
